---
title: Richard Joseph Barber, Composer
baseurl: "/"
permalink: "/:title/"
landing_template: home
palette: barber
palettes:
  barber:
    sass:
      gradient1: "#000000"
      gradient2: "#ffffff"
      accent1: "#5f9dd2"
      accent2: "#758ce1"
      accent3: "#e286a9"
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- LICENSE.md
- README.md
collections:
  pages:
    output: true
    permalink: /:name
  albums:
    output: true
    permalink: "/albums/:title"
